### ISSUE TITLE
Crash on launch?

### ISSUE THREAD

**Issue by Derpford** [Natanaelel/BankStorage#13]
**Describe the bug**
Game crashes on launch with a Critical Injection Failure due to injection conflicts with at least one other mod.

**To Reproduce**
1. Install both [Spyglass Astronomy](https://www.curseforge.com/minecraft/mc-mods/spyglass-astronomy) and Bank Storage.
2. Start game.
3. Crash.

**Expected behavior**
Game launches.

**Logs**
[crash-2024-02-03_14.27.20-client.txt](https://github.com/Natanaelel/BankStorage/files/14154457/crash-2024-02-03_14.27.20-client.txt)
[latest.log](https://github.com/Natanaelel/BankStorage/files/14154458/latest.log)

**Additional context**
I've got quite a few mods here, and I'm not in the mood to do extensive testing to see which other mods conflict. I know that a previous crash reported a conflict with [Packages](https://www.curseforge.com/minecraft/mc-mods/packages).

**Comment by Natanaelel** [comment]
I've found this is because both bankstorage and spyglass astronomy tries to replace the same minecraft code.
Bankstorage here: https://github.com/Natanaelel/BankStorage/blob/ff2c948daf92af6d142541cdf0aa77c7d09429bc/src/client/java/net/natte/bankstorage/mixin/MouseMixin.java#L18
Spyglass astronomy here: https://github.com/Nettakrim/Spyglass-Astronomy/blob/70f07ff1e69b2f8f6960f039bada19144a15abb1/src/main/java/com/nettakrim/spyglass_astronomy/mixin/MouseMixin.java#L35

I'll try to use another approach and spyglass astronomy should too.

**Comment by Nettakrim** [comment]
should be fixed now

**Comment by Natanaelel** [comment]
Nice. My fix in next release. Closing when that happens.

**Comment by Natanaelel** [comment]
fixed in 1.0.0
https://modrinth.com/mod/bank-storage/version/1.0.0
